# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:


- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker pull ${_REPO}/builders/benchmark/${_BENCHMARK} || exit 0

- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',

    # Use two tags so that the image builds properly and we can push it to the
    # correct location.
    '--tag',
    'gcr.io/fuzzbench/builders/benchmark/${_BENCHMARK}',

    '--tag',
    '${_REPO}/builders/benchmark/${_BENCHMARK}:${_EXPERIMENT}',

    '--file=benchmarks/${_BENCHMARK}/Dockerfile',

    '--cache-from',
    '${_REPO}/builders/benchmark/${_BENCHMARK}:${_EXPERIMENT}',

    'benchmarks/${_BENCHMARK}',
  ]
  id: 'build-project-builder'

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker pull ${_REPO}/builders/${_FUZZER}/${_BENCHMARK}-intermediate || exit 0
  id: 'pull-fuzzer-benchmark-builder-intermediate'
  wait_for: ['-']

- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',

    '--tag',
    'gcr.io/fuzzbench/builders/${_FUZZER}/${_BENCHMARK}-intermediate',

    '--tag',
    '${_REPO}/builders/${_FUZZER}/${_BENCHMARK}-intermediate:${_EXPERIMENT}',

    '--file=fuzzers/${_FUZZER}/builder.Dockerfile',

    '--cache-from',
    '${_REPO}/builders/${_FUZZER}/${_BENCHMARK}-intermediate',

    # Use a hardcoded repo because the parent image is pinned by SHA. Users
    # won't have it.
    '--build-arg',
    'parent_image=gcr.io/fuzzbench/builders/benchmark/${_BENCHMARK}',

    'fuzzers/${_FUZZER}',
  ]
  id: 'build-fuzzer-benchmark-builder-intermediate'
  wait_for: ['pull-fuzzer-benchmark-builder-intermediate', 'build-project-builder']

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker pull ${_REPO}/builders/${_FUZZER}/${_BENCHMARK} || exit 0
  id: 'pull-fuzzer-benchmark-builder'
  wait_for: ['-']

- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',

    '--tag',
    'gcr.io/fuzzbench/builders/${_FUZZER}/${_BENCHMARK}',

    '--tag',
    '${_REPO}/builders/${_FUZZER}/${_BENCHMARK}:${_EXPERIMENT}',

    '--file=docker/oss-fuzz-builder/Dockerfile',

    '--cache-from',
    '${_REPO}/builders/${_FUZZER}/${_BENCHMARK}',

    '--build-arg',
    'parent_image=${_REPO}/builders/${_FUZZER}/${_BENCHMARK}-intermediate',

    '--build-arg',
    'fuzzer=${_FUZZER}',

    '--build-arg',
    'benchmark=${_BENCHMARK}',

    '.',
  ]
  id: 'build-fuzzer-benchmark-builder'
  wait_for: ['pull-fuzzer-benchmark-builder', 'build-fuzzer-benchmark-builder-intermediate']

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker pull ${_REPO}/builders/${_FUZZER}/${_BENCHMARK}-intermediate || exit 0
  id: 'pull-fuzzer-benchmark-runner-intermediate'
  wait_for: ['-']

- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',

    '--tag',
    'gcr.io/fuzzbench/runners/${_FUZZER}/${_BENCHMARK}-intermediate',

    '--tag',
    '${_REPO}/runners/${_FUZZER}/${_BENCHMARK}-intermediate:${_EXPERIMENT}',

    '--file',
    'fuzzers/${_FUZZER}/runner.Dockerfile',

    '--cache-from',
    '${_REPO}/runners/${_FUZZER}/${_BENCHMARK}-intermediate',

    'fuzzers/${_FUZZER}',
  ]
  id: 'build-fuzzer-benchmark-runner-intermediate'
  wait_for: ['pull-fuzzer-benchmark-runner-intermediate', 'build-fuzzer-benchmark-builder']

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker pull ${_REPO}/builders/${_FUZZER}/${_BENCHMARK} || exit 0
  id: 'pull-fuzzer-benchmark-runner'
  wait_for: ['-']


- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',

    '--tag',
    'gcr.io/fuzzbench/runners/${_FUZZER}/${_BENCHMARK}',

    '--tag',
    '${_REPO}/runners/${_FUZZER}/${_BENCHMARK}:${_EXPERIMENT}',

    '--build-arg',
    'fuzzer=${_FUZZER}',

    '--cache-from',
    '${_REPO}/runners/${_FUZZER}/${_BENCHMARK}',

    '--build-arg',
    'benchmark=${_BENCHMARK}',

    '--file',
    'docker/benchmark-runner/Dockerfile',

    '.',
  ]
  wait_for: ['pull-fuzzer-benchmark-runner', 'build-fuzzer-benchmark-runner-intermediate']

images:
  - '${_REPO}/builders/benchmark/${_BENCHMARK}:${_EXPERIMENT}'
  - '${_REPO}/builders/${_FUZZER}/${_BENCHMARK}-intermediate:${_EXPERIMENT}'
  - '${_REPO}/builders/${_FUZZER}/${_BENCHMARK}:${_EXPERIMENT}'
  - '${_REPO}/runners/${_FUZZER}/${_BENCHMARK}-intermediate:${_EXPERIMENT}'
  - '${_REPO}/runners/${_FUZZER}/${_BENCHMARK}:${_EXPERIMENT}'
